Fixed a few things with the HF blade (hopefully)
Oasis-SS13/Oasis-SS13 pull request #770
Opened 2021-02-16 02:27 UTC by xDyouGamer

## About The Pull Request
-Only able to play music in brazil mode
-Cooldown between the music so you cant spam it like an idiot
-Pop req for the blade is now 20 to prevent cringe murderbone

## Why It's Good For The Game
no idea

## Changelog
:cl:
add: Fixes the HF blade
/:cl:

2021-02-20 01:15 UTC, ro5490 commented
@xDyouGamer 
![image](https://user-images.githubusercontent.com/17776299/108577467-2100a880-7319-11eb-9358-52125f294b19.png)

2021-02-20 22:12 UTC, MACIEKBAKI requested changes

2021-02-20 22:12 UTC, MACIEKBAKI commented on code/game/objects/items/melee/hfblade.dm
> +var/last_used = 0
remove this

2021-02-20 22:12 UTC, MACIEKBAKI commented on code/game/objects/items/melee/hfblade.dm
> +var/last_used = 0
and put it near the top where all the other vars are defined

2021-02-20 22:12 UTC, MACIEKBAKI commented on code/game/objects/items/melee/hfblade.dm
> +var/last_used = 0
```
	light_color = "#40ceff"
	var/rules_of_nature = TRUE // Turn this off to break the rules, and watch the horrors of no proximity flags unfold.
	var/brazil = FALSE
	var/brightness = 5
	var/cooldown = 40
	var/last_used = 0
```

is what you want

2021-03-06 05:11 UTC, ro5490 approved these changes

2021-03-06 05:11 UTC, merged