Mice in maints as ghost spawners
Oasis-SS13/Oasis-SS13 pull request #894
Opened 2021-03-03 18:56 UTC by OcelotTheOcelot

## About The Pull Request
This PR adds every mouse spawned in maintenance corridors to the ghost spawners menu. Mice are unable to communicate via speech until they gain sentience. Player-controlled mice now also have the ability to chew power cabels and die because of that as well as the original simplemobs used to.

## Why It's Good For The Game
Ghost players now gain the ability to squeak at the crew, to gnaw power cables and to organize a march into the SM crystal.

## Changelog
:cl:
add: maint mice ghost spawners
code: minor changes in mouse.dm
/:cl:

2021-03-03 19:24 UTC, TotallyNotChief commented
yes we
we are mice now

2021-03-03 19:30 UTC, TotallyNotChief requested changes

2021-03-03 19:30 UTC, TotallyNotChief commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	var/mouse_ask = alert("Do you really want to become a mouse?", "Become a mouse?", "Yes", "No")
```suggestion
	var/mouse_ask = alert("Do you really want to become a mouse?", "Become a mouse?", "Yes", "Yes")
```

2021-03-03 19:30 UTC, TotallyNotChief commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +		return
```suggestion

```

2021-03-03 19:45 UTC, TotallyNotChief commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +		return
no turning back

2021-03-03 21:13 UTC, ro5490 approved these changes
Looks pretty good, nice work

2021-03-03 21:21 UTC, Moccha-Bee commented
really based

2021-03-03 21:23 UTC, Kryyto commented
Work well, There is no description in the spawner menu though 
![image](https://user-images.githubusercontent.com/69859497/109874208-188c6400-7c6f-11eb-9a70-eb1eb4b8eee3.png)

2021-03-04 05:13 UTC, OcelotTheOcelot commented
> Work well, There is no description in the spawner menu though
> ![image](https://user-images.githubusercontent.com/69859497/109874208-188c6400-7c6f-11eb-9a70-eb1eb4b8eee3.png)

I don't know why doesn't it appear, I've overriden the 'get_spawner_desc' and 'get_spawner_flavour_text' procs tho. I will try to fix this in me next PR where I will also fix that SCP-173 issue.

2021-03-04 06:14 UTC, OcelotTheOcelot commented
There was a `isllime(O)` check in the spawners menu that only used `get_spawner_desc` when the object is a slime. As I can see, `get_spawner_flavour_text` returns atom's desc by default, therefore the `isslime(O)` check is redundant.
In case the spawner wasn't a slime, the `short_desc` field would stay an empty string, why not use `get_spawner_desc` instead, which returns atom's name by default?

2021-03-04 19:31 UTC, merged

2021-03-04 19:34 UTC, Kryyto commented
> 
> 
> There was a `isllime(O)` check in the spawners menu that only used `get_spawner_desc` when the object is a slime. As I can see, `get_spawner_flavour_text` returns atom's desc by default, therefore the `isslime(O)` check is redundant.
> In case the spawner wasn't a slime, the `short_desc` field would stay an empty string, why not use `get_spawner_desc` instead, which returns atom's name by default?

Honestly, I have no idea why ```isslime``` is a thing since it should work in any case, I guess it was made due to a bug that was fixed later on, and the guys forgot to remove it ?